// ADR-077 §D5 / §F2: complaint box schema.
//
// One row per anomaly that superdoctor (or an operator) files against
// a team. Schema field names match the SQL columns
// (`src/abstractions/sqlite-migrations.ts` v2) modulo snake/camel
// translation in the row↔domain bridge.
//
// `status` is intentionally a free-form string at the schema layer
// even though the verb constrains it to `open`/`resolved`/`wontfix`
// — the bias matches `KanbanTask.status` (passthrough on the schema,
// enum at the verb) so future statuses (e.g. `triaged`) can land
// without a schema break.
//
// `extra` is the forward-compat JSON bag — same pattern as
// `KanbanTask.extra`. The verb may stash structured fields here
// (e.g. `kind` for P0 escalations) without churning the schema.

import { z } from "zod";

/** Allowed values at the verb layer. Schema stays free-form (TEXT). */
export const COMPLAINT_STATUSES = ["open", "resolved", "wontfix"] as const;
export type ComplaintStatus = (typeof COMPLAINT_STATUSES)[number];

/** Allowed `sourceKind` values at the verb layer (v3 / t-e5e5d576).
 *  Schema stays free-form (TEXT) — same passthrough posture as
 *  `status`. Documented mapping to `openedBy` / `sourceId` lives on
 *  the task body + ADR follow-up. */
export const COMPLAINT_SOURCE_KINDS = [
  "superdoctor",
  "member",
  "operator",
  "cli",
  "cron",
] as const;
export type ComplaintSourceKind = (typeof COMPLAINT_SOURCE_KINDS)[number];

export const Complaint = z
  .object({
    /** Stable ID, conventionally `c-` + 8 hex chars (mirrors task ID
     *  pattern `t-...`). Generated by the verb on `file`. */
    id: z.string().min(1),
    /** Epoch seconds when the complaint was filed. */
    openedAt: z.number().int().nonnegative(),
    /** Free-form attribution: `superdoctor`, `<team>:<member>`, or `cli`. */
    openedBy: z.string().nullable().default(null),
    /** One-line summary of what happened. Required. */
    incidentSummary: z.string().min(1),
    /** One-sentence diagnosis. Optional at the schema layer; superdoctor's
     *  brief requires it but the verb accepts file-then-fill. */
    rootCause: z.string().nullable().default(null),
    /** Structural-fix proposal — the point of the complaint. Optional at
     *  the schema layer; ADR-077 §6 marks "preventive_ask_pending" in
     *  `extra` when it lands later. */
    preventiveAsk: z.string().nullable().default(null),
    /** `open` (default) | `resolved` | `wontfix`. Free-form at schema; the
     *  verb constrains. */
    status: z.string().default("open"),
    /** Epoch seconds when status flipped to resolved/wontfix. */
    resolvedAt: z.number().int().nonnegative().nullable().default(null),
    /** Attribution for the resolution. */
    resolvedBy: z.string().nullable().default(null),
    /** Kanban task ID that implements the preventive ask (when one exists). */
    relatedTaskId: z.string().nullable().default(null),
    /** Provenance kind (v3 / t-e5e5d576). Allowlist values live in
     *  `COMPLAINT_SOURCE_KINDS`; schema accepts any TEXT so v2 rows
     *  parse unchanged. */
    sourceKind: z.string().nullable().default(null),
    /** Structured source identifier (v3). e.g. `atmux:planner`,
     *  `sweep-1715290000`, `pid-12345`. Free-form at schema. */
    sourceId: z.string().nullable().default(null),
    /** Team this complaint is ABOUT (v3) — distinct from the team
     *  whose state.db holds the row. Enables cross-team filing
     *  (superdoctor on team A pinging about team B's bug). */
    targetTeam: z.string().nullable().default(null),
    /** Forward-compat JSON bag (parsed on read; serialized on write). */
    extra: z.record(z.string(), z.unknown()).default({}),
  })
  .passthrough();
export type Complaint = z.infer<typeof Complaint>;
